### ISSUE TITLE
Create monster table/schema

### ISSUE THREAD

**Issue by gieskj01** [8bitgaming/OgreQuest#3]
Store monster table in db.
Initial schema idea:
ID 
Monster Type/Name
Health
Attack
Defense
Gold Value/worth when defeated

**Comment by dwetoskey** [comment]
Initial seeds and model created. (monstersData.js, Monsters.js)
5 initial monsters with test data created.
Attributes in Monsters.js include id, name, hp, attack, and reward at this time.
