### ISSUE TITLE
create User/Character Schema

### ISSUE THREAD

**Issue by gieskj01** [8bitgaming/OgreQuest#4]
Potentially two tables/schemas - one for user and one for characters. Potential schema:
ID
Name
Health
Attack
Defense
Gold

**Comment by armcuellar** [comment]
The two schemas that will be created:
* Character Schema:
  * ID
  * Name
  * Health
  * Attack
  * Gold

* User Schema:
  * ID
  * username
  * email
  * password
  * characters_id (the characters associated with user)

**Comment by gieskj01** [comment]
Is email needed? We could probably get by with just username for now - my two cents. Feel free to disagree and put it in anyway :)

**Comment by armcuellar** [comment]
I will remove email, if needed I could always add it back.
